name: Run WMS Regress Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Newman and Allure
        run: |
          npm install -g newman newman-reporter-allure allure-commandline

      - name: Run Newman tests
        run: |
          newman run collections/WMS-regress.json -e environments/env-wms.json -r cli,allure --reporter-allure-export allure-results || true

      - name: Generate Allure report
        run: |
          allure generate allure-results -o allure-report --clean

      - name: Publish Allure report to gh-pages
        run: |
          REPORT_DIR=reports/regress/$(date +'%Y-%m-%d_%H-%M-%S')
          mkdir -p $REPORT_DIR
          cp -r allure-report/* $REPORT_DIR/

          # Клонируем только ветку gh-pages
          git clone --single-branch --branch gh-pages https://x-access-token:${GH_PAT}@github.com/${{ github.repository }} gh-pages

          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          mkdir -p $REPORT_DIR
          cp -r ../$REPORT_DIR/* $REPORT_DIR/
          touch .nojekyll

          git add .
          git commit -m "Publish regress report: $REPORT_DIR"
          git push origin gh-pages
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
